spring.application.name=reserva-Sovrano

# Porta da aplicação
server.port=8080

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ibike}
spring.datasource.username=${DB_USER:ibike}
spring.datasource.password=${DB_PASS:ibike}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging 
logging.level.org.springframework.web=INFO

# Development SMTP (MailHog)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.default-encoding=UTF-8
spring.mail.from=no-reply@sovrano.local


