spring.application.name=reserva-Sovrano

# Porta da aplicação
server.port=8080

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sovrano_db
spring.datasource.username=sovrano_user
spring.datasource.password=sovrano_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging (opcional)
logging.level.org.springframework.web=INFO
